version: "3.2"

services:
  delta-zk:
    build: .
    container_name: delta-zk
    image: "deltampc/delta-zk:dev"
    volumes:
      - ./ptau:/app/ptau
      - ./circuits/main:/app/circuits/main
    command: ["yarn", "test"]

      