version: "3.2"

services:
  delta-zk:
    build: .
    container_name: delta-zk
    image: "deltampc/delta-zk:dev"
    ports:
      - "4500:4500"
    volumes:
      - "./circuits/main:/app/circuits/main"